/** 初始方向档案：作为可编辑的规划起点，而非自动决策规则的唯一真相。 */
import type { TopicDirectionInput } from "../types.js";

export const DEFAULT_TOPIC_DIRECTIONS: TopicDirectionInput[] = [
  {
    id: "dir_code_agent_reliability", topic_id: "t_code_agents", name: "Agentic SDLC 的可靠性与评测",
    objective: "建立可衡量、可回归验证的代码 Agent 可靠性能力。",
    problem_statement: "代码 Agent 的任务成功率、失败模式和人类接管边界缺少统一评测与工程护栏。",
    in_scope: ["代码 Agent 评测", "SWE-bench", "任务可靠性", "失败分析"], out_of_scope: ["通用商业化动态"],
    key_questions: ["如何定义端到端任务成功？", "哪些失败可被自动检测和回滚？"], constraints: ["可复现", "成本可控"],
    success_signals: ["代表性任务集的可重复基准", "失败类型与防护措施的对应关系"],
    match_terms: ["swe-bench", "benchmark", "eval", "evaluation", "评测", "基准", "reliability", "可靠性"],
    adjacent_terms: ["agent", "copilot", "code review", "代码审查"], challenge_terms: ["regression", "failure", "失败", "不可靠"], horizon: "now", status: "active",
  },
  {
    id: "dir_code_context_engineering", topic_id: "t_code_agents", name: "上下文、Spec 与 Skills 工程",
    objective: "让代码 Agent 的上下文、规范和技能能够组合、审计与复用。",
    problem_statement: "上下文管理和任务规范不稳定会导致 Agent 输出不可预测、难复盘。",
    in_scope: ["context engineering", "spec", "skills", "provenance"], out_of_scope: ["纯模型融资消息"],
    key_questions: ["规范如何成为可执行约束？", "上下文与技能如何版本化和追溯？"], constraints: ["兼容现有开发流", "可审计"],
    success_signals: ["可复用的规范 / 技能资产", "可追溯的上下文变更记录"],
    match_terms: ["context engineering", "prompt engineering", "spec", "skills", "provenance", "traceability", "上下文", "规范", "技能", "可追溯"],
    adjacent_terms: ["workflow", "harness", "agentic swe", "开发工作流"], challenge_terms: ["context window", "hallucination", "幻觉", "上下文丢失"], horizon: "now", status: "active",
  },
  {
    id: "dir_code_agent_security", topic_id: "t_code_agents", name: "代码 Agent 的安全与可控执行",
    objective: "降低代码 Agent 在工具调用、依赖和执行环境中的安全风险。",
    problem_statement: "自主执行带来供应链、权限扩大和不安全代码变更风险。",
    in_scope: ["agent security", "tool permission", "software supply chain"], out_of_scope: ["非工程场景的一般安全新闻"],
    key_questions: ["如何最小化工具权限？", "怎样在合并前验证 Agent 修改？"], constraints: ["不显著降低开发效率"],
    success_signals: ["可执行的权限与审批模型", "针对代码 Agent 的攻击 / 防护测试"],
    match_terms: ["agent security", "supply chain", "dependency", "permission", "sandbox", "安全", "供应链", "权限", "沙箱"],
    adjacent_terms: ["vulnerability", "cve", "attack", "漏洞", "攻击"], challenge_terms: ["prompt injection", "data exfiltration", "越权", "泄露"], horizon: "next", status: "active",
  },
  {
    id: "dir_security_prompt_injection", topic_id: "t_prompt_injection", name: "Prompt Injection 检测与防御",
    objective: "构建可测试的注入攻击检测、隔离和缓解能力。",
    problem_statement: "Agent 和检索链路会把不可信输入提升为指令，传统边界不足以阻断。",
    in_scope: ["prompt injection", "jailbreak", "guardrails", "untrusted input"], out_of_scope: ["不含 AI 系统边界的通用安全动态"],
    key_questions: ["攻击如何被分类和复现？", "防御如何量化误报与漏报？"], constraints: ["对正常任务影响可量化"],
    success_signals: ["攻击集与防御回归测试", "明确的信任边界模型"],
    match_terms: ["prompt injection", "jailbreak", "guardrail", "indirect prompt", "提示注入", "越狱", "护栏"],
    adjacent_terms: ["agent", "tool use", "retrieval", "代理", "工具调用", "检索"], challenge_terms: ["bypass", "evasion", "绕过", "失效"], horizon: "now", status: "active",
  },
  {
    id: "dir_security_agent_runtime", topic_id: "t_prompt_injection", name: "Agent 红队与运行时防护",
    objective: "把 Agent 攻防从静态规则提升到运行时可观测、可响应的防护。",
    problem_statement: "多工具 Agent 的攻击路径跨越模型、权限、网络和数据边界，缺少统一运行时治理。",
    in_scope: ["agent red teaming", "runtime security", "tool policy", "incident response"], out_of_scope: ["纯合规或资本市场消息"],
    key_questions: ["怎样发现高风险工具链？", "出现攻击迹象时如何最小化影响？"], constraints: ["保留审计证据", "低延迟"],
    success_signals: ["红队场景库", "运行时告警和响应闭环"],
    match_terms: ["red team", "runtime security", "tool policy", "incident response", "红队", "运行时", "自动响应"],
    adjacent_terms: ["security agent", "threat detection", "soc", "威胁检测"], challenge_terms: ["agent attack", "tool abuse", "攻击链", "工具滥用"], horizon: "now", status: "active",
  },
  {
    id: "dir_security_model_supply_chain", topic_id: "t_prompt_injection", name: "模型与 AI 供应链安全",
    objective: "识别模型、数据、依赖和部署链的可验证安全控制点。",
    problem_statement: "模型权重、训练数据、依赖和推理服务均可能成为供应链攻击面。",
    in_scope: ["model security", "model extraction", "data poisoning", "ai supply chain"], out_of_scope: ["非技术政策讨论"],
    key_questions: ["哪些链路最需完整性验证？", "怎样验证模型和数据来源？"], constraints: ["可适配开源与闭源模型"],
    success_signals: ["可执行的供应链控制清单", "攻击复现与缓解验证"],
    match_terms: ["model extraction", "data poisoning", "model poisoning", "ai supply chain", "模型提取", "数据投毒", "供应链"],
    adjacent_terms: ["open weight", "dependency", "provenance", "开源权重", "依赖"], challenge_terms: ["backdoor", "poison", "后门", "投毒"], horizon: "next", status: "active",
  },
  {
    id: "dir_industry_model_readiness", topic_id: "t_ai_industry", name: "基础模型与工具链成熟度信号",
    objective: "为技术主题提供模型、评测、部署与生态成熟度的外部证据。",
    problem_statement: "基础模型变化影响技术路线可行性，但产业新闻不应直接替代技术立项证据。",
    in_scope: ["model release", "benchmark", "api", "developer tool"], out_of_scope: ["融资、IPO、估值"],
    key_questions: ["能力变化是否已被独立评测？", "生态是否足以支持试点？"], constraints: ["作为外部证据，不自动立项"],
    success_signals: ["可复核的能力或部署变化", "对其他主题有明确影响"],
    match_terms: ["model release", "benchmark", "api", "sdk", "模型发布", "评测", "开发者工具"],
    adjacent_terms: ["open source", "open weight", "deployment", "开源", "部署"], challenge_terms: ["regression", "safety incident", "能力退化", "安全事件"], horizon: "explore", status: "active",
  },
];
