/** Synthetic IPC fixture: keys are generated by tests, never loaded from environment/files. */
import { createPrivateKey, createPublicKey } from "node:crypto";
import { DurableSyntheticAuthority } from "../../experiments/c1-recovery/durable.js";

process.once("message", (input: { path: string; epoch: string; pem: string; mode: "batch" | "pending" | "freeze"; prefix: string; count: number }) => {
  const key = createPrivateKey(input.pem);
  const authority = DurableSyntheticAuthority.open(input.path, input.epoch, key, createPublicKey(key));
  if (input.mode === "pending") {
    const token = authority.begin();
    process.send?.({ token });
    // Parent kills this process after acknowledgement; no DB close/abort runs.
    setInterval(() => undefined, 1000);
    return;
  }
  try {
    if (input.mode === "batch") {
      for (let i = 0; i < input.count; i++) authority.commit(authority.begin(), { key: `${input.prefix}/${i}`, version: "v1", body: `synthetic-${i}` });
      process.send?.({ done: true });
    } else if (input.mode === "freeze") {
      try { authority.freeze("2026-03-01T00:00:00Z"); process.send?.({ frozen: true }); }
      catch { process.send?.({ refused: true }); }
    }
  } finally { authority.close(); process.disconnect?.(); }
});
